# Generated by Django 3.0.8 on 2020-07-24 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 18, 31, 29, 845621), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 18, 31, 29, 845621), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='images/pictures/user_default.png', null=True, upload_to='images/pictures'),
        ),
    ]
