# Generated by Django 3.0.8 on 2020-07-15 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200715_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pictures'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 19, 34, 876467), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 19, 34, 878464), verbose_name='created at'),
        ),
    ]
