# Generated by Django 3.0.8 on 2020-08-02 16:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200801_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 11, 26, 53, 812817), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 11, 26, 53, 813816), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
