# Generated by Django 3.0.8 on 2020-08-02 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200802_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 11, 18, 294225), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 12, 11, 18, 295225), verbose_name='created at'),
        ),
    ]
