# Generated by Django 3.0.8 on 2020-08-27 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200811_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 1, 5, 56, 45363), verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='relationshiprequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 1, 5, 56, 46363), verbose_name='created at'),
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='accounts.UserProfile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.UserProfile')),
            ],
        ),
    ]
