# Generated by Django 3.0.8 on 2020-07-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
