# Generated by Django 3.0.8 on 2020-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200730_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicaction',
            name='image',
            field=models.ImageField(default='images/topicholder.png', upload_to='topimages/'),
        ),
    ]
