# Generated by Django 3.0.8 on 2020-07-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200707_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='approved',
        ),
    ]
