# Generated by Django 3.0.8 on 2020-08-01 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200730_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_set', to='feed.Topic'),
        ),
    ]
