# Generated by Django 3.0.8 on 2020-07-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_feed_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-hot_topics']},
        ),
        migrations.AddField(
            model_name='feed',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='hot_topics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
