# Generated by Django 3.0.8 on 2020-08-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200731_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Topic'),
        ),
    ]
