# Generated by Django 3.0.8 on 2020-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200801_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
