# Generated by Django 3.0.8 on 2020-07-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200709_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicManager',
        ),
    ]
