# Generated by Django 3.0.8 on 2020-08-02 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200802_1211'),
        ('feed', '0007_auto_20200802_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='feed_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='view_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds_viewed', to='accounts.UserProfile'),
        ),
    ]
