# Generated by Django 3.0.8 on 2020-08-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200802_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
