# Generated by Django 3.0.8 on 2020-07-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20200709_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='topimages/%Y/%m/%d/'),
        ),
    ]
