# Generated by Django 3.0.8 on 2020-08-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20200808_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
