# Generated by Django 3.0.8 on 2020-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20200808_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
