# Generated by Django 3.0.8 on 2020-07-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20200713_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.Feed'),
        ),
    ]
