# Generated by Django 3.0.8 on 2020-07-14 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20200713_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='is_published',
        ),
        migrations.AddField(
            model_name='feed',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'verified'), (3, 'published')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, default=1, validators=[django.core.validators.MinLengthValidator(150)]),
            preserve_default=False,
        ),
    ]
