# Generated by Django 3.0.8 on 2020-08-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_reply_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='topicaction',
            name='image',
            field=models.ImageField(blank=True, default='images/topicholder.png', null=True, upload_to='topimages/'),
        ),
    ]
