# Generated by Django 3.0.8 on 2020-08-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20200821_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, default='photos/feedholder.png', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
