# Generated by Django 3.0.8 on 2020-08-27 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20200821_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(160)]),
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
