# Generated by Django 3.0.8 on 2020-07-17 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20200716_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
