# Generated by Django 3.0.8 on 2020-07-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20200716_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
    ]
